# Generated by Django 3.2.7 on 2021-09-15 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_user_date_joined"),
    ]

    operations = []
