# Generated by Django 3.2.7 on 2021-09-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_user_devices"),
    ]

    operations = []
