# Generated by Django 3.2.7 on 2021-09-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('accounts', '0020_alter_user_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='devices',
            field=models.ManyToManyField(to='devices.Device'),
        ),
    ]
