# Generated by Django 3.2.7 on 2021-10-26 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preference',
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preference',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.theme'),
        ),
    ]
