# Generated by Django 3.2.7 on 2021-10-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_preference_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='user',
            new_name='user_preference',
        ),
    ]
