# Generated by Django 3.2.7 on 2021-10-26 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_rename_user_preference_user_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='user_preference',
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL),
        ),
    ]
