# Generated by Django 3.2.7 on 2021-10-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20211026_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='preference',
            new_name='user',
        ),
    ]
