# Generated by Django 3.2.7 on 2021-09-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=8),
        ),
    ]
