# Generated by Django 3.2.7 on 2021-10-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observers', '0003_alter_observer_status'),
        ('devices', '0003_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='observers',
            field=models.ManyToManyField(blank=True, to='observers.Observer'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(default='offline', max_length=8, verbose_name=[('active', 'Active'), ('inactive', 'Inactive'), ('online', 'Online'), ('offline', 'Offline')]),
        ),
        migrations.CreateModel(
            name='DeviceObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('status', models.CharField(default='offline', max_length=8, verbose_name=[('active', 'Active'), ('inactive', 'Inactive'), ('online', 'Online'), ('offline', 'Offline')])),
                ('observer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observers.observer')),
            ],
        ),
    ]
