# Generated by Django 3.2.7 on 2021-10-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observers', '0002_observer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observer',
            name='status',
            field=models.CharField(default='draft', max_length=8, verbose_name=[('published', 'Published'), ('draft', 'Draft')]),
        ),
    ]
