# Generated by Django 3.2.7 on 2021-09-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210913_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='variants',
            new_name='variant',
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.preference'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='default', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='theme',
            unique_together={('variant', 'name')},
        ),
    ]
