# Generated by Django 3.2.7 on 2021-09-17 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='default', max_length=12, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
